<?php
if ($_SERVER['HTTP_HOST'] == "localhost:8080" || $_SERVER['HTTP_HOST'] == "localhost" ||  $_SERVER['HTTP_HOST']=="127.0.0.1")
{
	define("HOST","localhost");
	define("USER","root");
	define("PASS","shirshak17");
	define("DBNAME","db_lyrics");
}
else
{
	/*define("HOST","localhost");
	define("USER","lyricsne_dbnepal");
	define("PASS","90s-~S=fID3_");
	define("DBNAME","lyricsne_dbnepal");*/
	define("HOST","localhost");
	define("USER","lyricsne_lyrics");
	define("PASS","^-o%%aBZ5fVE");
	define("DBNAME","lyricsne_lyrics");
}
?>